### ISSUE TITLE
Are clone instances correctly correctly included in their reference definition's references?

### ISSUE THREAD

**Issue by andrewmkeller** [byuccl/spydrnet#101]
It appears that when an instance is cloned, its reference definition is completely unaware of the new instance. This is not desired behavior unless the supporting definition was cloned as well (which could be the case). Reguardless, the referenced definition should always include the referencing instance in its references.

**Comment by thunder-hammer** [comment]
I agree. I think it is even documented as you say. I'll work on this. since 1.4 is mostly a minor release it might not hurt to just include it there. is there an advantage to creating a 1.3.1 build?

**Comment by thunder-hammer** [comment]
I just made sure this works and it looked good. I'm going to close the issue.
