### ISSUE TITLE
Tutorial into the documentation

### ISSUE THREAD

**Issue by thunder-hammer** [byuccl/spydrnet#105]
It would be awesome to have some tutorials that show up in the documentation nicely. This would hopefully give someone an introduction to SpyDrNet who has never used the tool before.

We already have some examples. We could include them in the documentation or perhaps do a simple parse compose example to our own serialized intermediate representation. something like that would be really nice. this would include explanations as needed and perhaps a line by line break down to make the example work well for someone who is just being introduced to the tools.

**Comment by jordi1215** [comment]
I noticed that there is a clone file that is not connected to any toctree

**Comment by thunder-hammer** [comment]
Good catch. That should probably be added in somewhere. perhaps as a subsection under reference.

**Comment by thunder-hammer** [comment]
I think @jordi1215 has made a lot of progress on this. Could you update this issue for us please? Our documentation looks awesome.

**Comment by jacobdbrown4** [comment]
Jordi's tutorial is good! Now I'm going to start working on making improvements to it for the next release.

**Comment by jacobdbrown4** [comment]
I went through and improved the tutorial. It should be good for now. Closing the issue...
