### ISSUE TITLE
Hierarchy viewer

### ISSUE THREAD

**Issue by thunder-hammer** [byuccl/spydrnet#11]
This is a low priority issue. We could include a viewer in our tool to view the netlists.

**Comment by thunder-hammer** [comment]
A recursive hierarchy viewer is being worked on by @jacobdbrown4 

It will be included in the examples as a way to visualize the netlist.

Because some netlists are too deep to show through recursion in python this will stay as just an example.

I am going to add this on to the next release project.

**Comment by thunder-hammer** [comment]
@jacobdbrown4, not sure if this made it into the 1.8.1 release update. if so feel free to close the issue.

**Comment by jacobdbrown4** [comment]
I added the hierarchy viewing function to the examples, so this should be good for now. I'll close the issue.
