### ISSUE TITLE
Virtual Instance Netlist Integration

### ISSUE THREAD

**Issue by andrewmkeller** [byuccl/spydrnet#12]
Virtual objects allow any element in the net list to be identified uniquely through hierarchically. In other words, a virtual object is guaranteed to be unique even if the underlying instance or definition is not unique. Hierarchy allows the same resource to be utilized more than once in different places. This creates some confusion when it comes to modifying a netlist. We are adding virtual objects so that they can be maintained by netlist as it changes.

What needs to happen here:

When a top_level_instance is created and assigned, an accompanying virtual instance needs created and populated and a pointer needs to be added to a set of virtual instance pointers in the  definition being instanced. When an instance is added or removed in the actual netlist, that change needs to be reflected in the virtual instance hierarchy.

**Comment by thunder-hammer** [comment]
Since this has been marked as done I am closing the issue.
