### ISSUE TITLE
API Completeness version 1.0.0

### ISSUE THREAD

**Issue by andrewmkeller** [byuccl/spydrnet#16]
Here are the function call supported by our release:

import spydrnet as sdn

SDN Level

????? <- Chararitoristics of primitive cells

IS_SEQUENTIAL
IS_FLIP_FLOP

sdn.create_netlist
sdn.add_netlist
sdn.remove_netlist
sdn.get_netlists

?????

sdn.get_designs
sdn.get_top_level_instance
sdn.get_libraries
sdn.get_definitions
sdn.get_ports
sdn.get_cables
sdn.get_instances
sdn.get_inner_pins
sdn.get_outer_pins
sdn.get_pins?
sdn.get_instantance
sdn.get_wires

?????

sdn.remove_cables
sdn.remove_instances
sdn.remove_ports
sdn.remove_definitions
sdn.remove_libraries

Netlist (Environment) Level # Renamed from Environment to Netlist

sdn.Netlist()
netlist.design
netlist.libraries
netlist.create_library
netlist.add_library
netlist.remove_library
netlist.get_libraries

Library Level

sdn.Library()
library.environment
library.definitions
library.create_definition
library.add_definition
library.remove_definition
library.get_definitions

Definition Level

sdn.Definition()
definition.library
definition.ports
definition.cables
definition.instances
definition.is_leaf # no instances, no cables, only ports
definition.create_port
definition.add_port
definition.remove_port
definition.get_ports
definition.create_cable
definition.add_cable
definition.remove_cable
definition.get_cables
definition.create_instance
definition.add_instance
definition.remove_instance
definition.get_instances

Port Level (Bundle)

sdn.Port()
port.definition
port.is_downto
port.is_scalar
port.lower_index
port.pins # from inner_pin
port.direction
port.initialize_pins
port.initialize_pins_in_range
port.set_direction
port.create_pin
port.add_pin
port.remove_pin
port.get_pins

Inner Pin Level (Pin)

sdn.InnerPin()
pin.port 
pin.wire # wire that it is connected to

Outer Pin Level (Pin)

sdn.OuterPin()
pin.instance
pin.inner_pin
pin.wire

Cable Level (Bundle)

sdn.Cable()
cable.definition
cable.is_downto
cable.is_scalar
cable.lower_index
cable.wires
cable.initialize_wires
cable.create_wire
cable.add_wire
cable.remove_wire
cable.get_wires

Wire Level

sdn.Wire()
wire.cable
wire.pins
wire.connect_pin
wire.disconnect_pin

Instance Level

- [x] sdn.Instance()
instance.parent # _definition
instance.definition # -> warning error type thing reference_definition?
instance.reference # Instance is an "instance" of the referenced definition.
instance.pins # from outer_pins
instance.is_leaf
instance.get_pins
#instance.get_pin
#instance.get_outer_pin

**Comment by thunder-hammer** [comment]
Since we released api 1.0.0 I think we should close this issue.
