### ISSUE TITLE
Extending SpyDrNet classes to implement application specific package

### ISSUE THREAD

**Issue by ganeshgore** [byuccl/spydrnet#160]
**Summary**
The core library of SpyDrNet is very well designed. I could imagine many different applications which can extend this library as per their need. I was wondering about the better ways to extending its classes and create a separate package. 

The best way could come up with is python plugin system architecture. Following are some of the modules which implement the plugin/extension systems. like `pytest-**` for plugins for `pytest `. This will enable the development of other packages (like `spydrnet-physical`, `spydrnet-sta`, `spydrnet-tmr` etc.) without any limitation  

https://docs.pytest.org/en/latest/reference/plugin_list.html
https://pypi.org/search/?q=flask&o=&c=Framework+%3A%3A+Flask

**Difference from existing plugin system** 
I notices a plugin-like functionality already exists in the repo, but it mostly supports the callback system, which is very helpful to keep performing some tasks in parallel., but to extend any exiting class seems difficult (will require monkey-patching). 
Whereas, the idea in this proposal is to allow extending original classes themselves from the separate packages. 

Maybe to avoid confusion we can call it an extension system

**Evaluation/Experiements** 
As proof of the concept and for experimentation, I created a sample setup (you can find that in the following repo), which creates a simple `SpyDrNet` module and try to extend that with the `spydrnet_physical` package 
https://github.com/ganeshgore/spydrnet-plugin-test

In CI run you can see the original definition class from (`spydrnet `package) is extended by definition class in (`spydrnet_physical`). create_port method is from the original `spydrnet` module and merge_port is from the `spydrnet_physical `module.
https://github.com/ganeshgore/spydrnet-plugin-test/runs/3935287509?check_suite_focus=true#step:4:1

Let me know what do you think

**Comment by benglines** [comment]
https://packaging.python.org/guides/creating-and-discovering-plugins/

**Comment by wirthlin** [comment]
> https://packaging.python.org/guides/creating-and-discovering-plugins/

It seems that Ganesh's approach follows the 1st style listed in this article: "Using naming conventions"

**Comment by ganeshgore** [comment]
@wirthlin that's true, however, this is just a plugin discovery, how to integrate found plugin with the base project is not given in this documentation

**Comment by jacobdbrown4** [comment]
I have created a new branch called v.2.0-development. @ganeshgore can you create pull request to that branch for the version of spydrnet with extending classes?

**Comment by jacobdbrown4** [comment]
I've been looking into how pytest does its plugins. I found a lot of good stuff but don't understand how a lot of it works.

[Pytest Plugin List](https://github.com/pytest-dev/pytest/blob/main/doc/en/reference/plugin_list.rst)
[Pytest Plugin Manager](https://github.com/pytest-dev/pytest/blob/3dc17f1c3b266263723e66363750796262165686/src/_pytest/config/__init__.py#L335)
[Pytest How to Install and Use Plugins](https://github.com/pytest-dev/pytest/blob/main/doc/en/how-to/plugins.rst)
[Pytest Writing Plugins](https://github.com/pytest-dev/pytest/blob/main/doc/en/how-to/writing_plugins.rst#id22)

There's probably a lot we can learn from Pytest and how they do their plugins.

**Comment by jacobdbrown4** [comment]
@ganeshgore we've been doing more digging into your code that you have written for this and we have one question. In the clone functions, you explicitly import the extended version of the class, where it looks like you wouldn't need to. An example is in [cable](https://github.com/ganeshgore/spydrnet/blob/5e38fcf799906af79fb784525a78c0542e98dbed/spydrnet/ir/cable.py#L162). Can you clarify for us why that is needed?

Besides that, as soon as your pull request for the code to support class extension is ready we'll be ready to move forward.

**Comment by ganeshgore** [comment]
Hello @jacobdbrown4 
So most of the top imports are changed from `from spydrnet.ir.** import **` to `from spydrnet.ir import **`  which ensure that every object created is of extended version
However is clone functions, the class makes the object of itself (without explicitly importing) which is not actually an extended version 
The explicit import  ensure that the cloned object is an object of the extended class, 
I have done that in a couple more places in `outpin` and `innerpin` classes 
The final IR classes are available in `from spydrnet.ir` only, any other places just holds partial description.

**Comment by ganeshgore** [comment]
> I found a lot of good stuff but don't understand how a lot of it works.

These are very nice resources, I will see if I can find anything similar to what I am doing.

**Comment by ganeshgore** [comment]
> Besides that, as soon as your pull request for the code to support class extension is ready we'll be ready to move forward.

I have been a little busy with other work, I will try to do that over the weekend or early next week

**Comment by jacobdbrown4** [comment]
I see that in the __init__.py file, it looks for a .spydrnet file in the home directory to specify what plugins to use. Do we want the .spydrnet file be in the home directory? I feel like having it in the current directory would be better so that different projects can have different .spydrnet files.

**Comment by ganeshgore** [comment]
@jacobdbrown4 yes that makes sense, we can create a hierarchy of local dir, home dir and then environment variables

**Comment by jacobdbrown4** [comment]
I just started working on creating documentation for extensions before we release it and I should be finished soon. @ganeshgore is it okay with you if I include a link to your spydrnet_physical repository in our documentation?

**Comment by ganeshgore** [comment]
Sure, that will be a good reference for other developers.

**Comment by jacobdbrown4** [comment]
I merged all the changes into the master branch. It's part of the spydrnet 1.10.0 release. Let me know if you find any problems with the extending class functionality.

**Comment by ganeshgore** [comment]
It has been working great since the 1.10.0 release; I will close this issue now.
