### ISSUE TITLE
`requests` package dependency not in setup.py

### ISSUE THREAD

**Issue by jgoeders** [byuccl/spydrnet#212]
There is a dependency on the requests package, that is not marked as an installed dependency by the `setup.py` installer.

https://github.com/byuccl/spydrnet/blob/d5b9bd8313dce511fdc583c3451d290ba0ac3178/spydrnet/__init__.py#L17

**Comment by jacobdbrown4** [comment]
Thanks for reporting this.

**Comment by jacobdbrown4** [comment]
I believe I have fixed the issue with this commit: 733e7b0. It will be released into master soon
