### ISSUE TITLE
figure out webpage for project

### ISSUE THREAD

**Issue by andrewmkeller** [byuccl/spydrnet#22]
- [x] simple landing page in main folder of gh-pages branch (similar to networkx.github.io)
- [x] make a folder in gh-pages branch 'spydrnet-1.0'
- [x] once relase is ready, build static page, and add to created folder.
- [ ] test functionality and make sure it works.

**Comment by thunder-hammer** [comment]
I feel like this issue is likely mostly resolved. Would it be okay to close or is there more that needs to be done?
