### ISSUE TITLE
Upload source for ExampleCircuit.svg and include the figure somewhere in the documentation

### ISSUE THREAD

**Issue by andrewmkeller** [byuccl/spydrnet#62]

**Comment by thunder-hammer** [comment]
I created the image with inkscape. I'm not sure there is any other source. I did pull the circuit elements off of wikimedia commons they were licensed under CC0 or the public domain I don't recall which. I could upload those individually if it would be helpful.

**Comment by andrewmkeller** [comment]
Can you edit a svg with inkscape or do you need a different file? I like
the image, but I want to make sure we can move things around if ever we
need to.

**Comment by thunder-hammer** [comment]
Good question. I just did some research. Inkscape adds some information to the SVG to make it editable as it was when it was closed. I uploaded the one that is editable in inkscape. So I think it should be good to go.

**Comment by andrewmkeller** [comment]
Actually, we haven't added this figure to the documentation anywhere...

**Comment by thunder-hammer** [comment]
The figure is now available at https://byuccl.github.io/spydrnet/docs/stable/reference/api_specification.html
