### ISSUE TITLE
API shortcuts which would be useful to add.

### ISSUE THREAD

**Issue by thunder-hammer** [byuccl/spydrnet#79]
This is a list of different shortcuts that would be super useful to include in the API. There is currently a long way to do all of these things. It would be useful to add the following shortcuts into the API to make the tools easier to use and work with.

 - [ ] set the top instance
Long way:
`top = Instance()`
`top.reference = top_definition`
`netlist.top_instance = top`
could be simplified to:
`netlist.top_instance = top_definition`

 - [ ] create an alias to is_flat() in the instances
Long way:
`instance.reference.is_leaf()`
simplified to
`instance.is_leaf()`

 - [ ] wire index lookup
Long way:
`wire.cable.wires.index(wire)`
simplified to:
`wire.index`

 - [ ] add some key values to the constructors of elements
Definitions, Libraries, Netlists, instances, cables, and ports, could all use the following initilization parameters:
 - name
 - properties
cables and ports could use the following
 - downto
 - width
Example long way
`d = Definition()`
`d.name = "my_def"`
example shortcut
`d = Definition(name = "my_def")`
in the implementation defaults should be used to maintain current behaviour.

**Comment by thunder-hammer** [comment]
@andrewmkeller If you have any suggestions for the hrefs feel free to comment or edit the initial comment.

**Comment by thunder-hammer** [comment]
Have fun with testing. I've found it super useful. Going into the weekly meetings if I can say I have good tests with 100% code coverage It really gives a good boost of confidence.

The following are some generic ideas for testing that might be useful.

make sure the code works the way it was expected to work. for example using the short cut and long way should yield the same result.

take a look at how to break the test. for example make sure assertions are thrown if a wire does not belong to a cable or an instance does not have a reference. If there is a way to make sure the error message makes some sense that could be really helpful down the line too.

Find other strange but good use cases, and potential abuses and find a way to set up those circumstances to see if the code still holds up.

**Comment by thunder-hammer** [comment]
There are a few more shortcuts which would be useful

Basically the same shortcuts for the first class elements constructors from above would be useful to add to the parent's children constructors for example

`library.create_definition(name = "my_def")`
`definition.create_port(width = 32, downto = True)`

and so on for all of the first class element .create_* calls in the api to mirror the __init__ functions.

**Comment by thunder-hammer** [comment]
@jordi1215 I think you implemented most of this, could you update this issue please?

**Comment by jacobdbrown4** [comment]
@jordi1215 has implemented these (at least the ones deemed useful/necessary).
