### ISSUE TITLE
Edif composer is currently depenedent on EDIF.original_identifer

### ISSUE THREAD

**Issue by andrewmkeller** [byuccl/spydrnet#90]
We need to remove this dependency, we are currently probably dropping the original name.

['.NAME'] is the defacto name.
['EDIF.identifier'] is the idenfier.

if they don't match, the top one is the "original_identifier", use a rename or if "EDIF.rename" is set true use a rename.

**Comment by thunder-hammer** [comment]
This should be fixed now. let me double check before I close this issue.

**Comment by thunder-hammer** [comment]
I think this does not rely explicitly on the EDIF.identifier key. it will create it if it needs it.
